package generator

//
//import (
//	"bufio"
//	"fmt"
//	"go/ast"
//	"go/parser"
//	"go/token"
//	"os"
//	"path/filepath"
//	"strings"
//	"text/template"
//)
//
//// 生成导入代码的模板（新增日志提示）
//const routeImportTpl = `// Code generated by go-common auto-gen; DO NOT EDIT.
//// 警告：此文件由go-common自动生成，删除/修改会导致路由注册失效！
//package {{.PackageName}}
//
//import (
// "fmt"
//{{range .Routes}}
//	_ "{{.ModuleName}}/{{.Path}}"
//{{end}}
//)
//
//// Init 核心函数：防止编译器优化掉上述路由包的导入
//// 🔴 重要提醒：请勿删除/修改此函数！
//// 作用：即使没有其他代码引用这些路由包，编译器也会保留导入，触发路由包的init()函数执行
//// 删除后果：所有路由包的init()不会执行，路由注册失效，接口404
//func init() {
//	// 启动时打印提示，强化认知（仅debug级别，不影响生产）
//	if true { // 避免编译器优化掉日志（实际可结合log级别控制）
//		fmt.Printf("[路由自动导入] 已加载 %d 个路由包，Init()函数正常生效（请勿删除此函数）\n", len([]interface{}{ {{range .Routes}}nil,{{end}} }))
//	}
//}
//`
//
//// RouteGenInfo 路由包信息
//type RouteGenInfo struct {
//	ModuleName string // 业务项目的go module名（如pano-material）
//	Path       string // 路由包相对路径（如test、lecture）
//}
//
//// RouteGenConfig 生成配置
//type RouteGenConfig struct {
//	PackageName string         // 生成文件的包名（默认routes）
//	Routes      []RouteGenInfo // 扫描到的路由包
//}
//
//// AutoGenRouteImport 自动生成路由导入代码（支持通配符匹配）
//// 参数说明：
//// - moduleName: 业务项目的go module名（必填，如pano-material）
//// - scanRoot: 扫描的根目录（默认当前目录，传""则用当前工作目录）
//// - outputDir: 生成文件的目录（默认routes）
//// - matchPatterns: 通配符匹配规则（逗号分隔，默认test,lecture,handler,*Route,*router）
//// - ignoreDirs: 忽略的目录关键词（逗号分隔，默认vendor,testdata,docs）
//func AutoGenRouteImport(moduleName, scanRoot, outputDir, matchPatterns, ignoreDirs string) error {
//	// 1. 参数默认值处理
//	if scanRoot == "" {
//		var err error
//		scanRoot, err = os.Getwd() // 获取当前工作目录
//		if err != nil {
//			return fmt.Errorf("获取当前目录失败：%v", err)
//		}
//	}
//	if outputDir == "" {
//		outputDir = "routes" // 默认生成到routes目录
//	}
//	// 默认支持的通配符规则：精确匹配+模糊匹配
//	if matchPatterns == "" {
//		matchPatterns = "test,lecture,handler,*Route,*router,handler/*"
//	}
//	if ignoreDirs == "" {
//		ignoreDirs = "vendor,testdata,docs,node_modules,.git,.idea"
//	}
//	if moduleName == "" {
//		return fmt.Errorf("moduleName不能为空（请传入业务项目的go module名，如pano-material）")
//	}
//
//	// 2. 创建routes目录（不存在则创建）
//	if err := os.MkdirAll(outputDir, 0755); err != nil {
//		return fmt.Errorf("创建routes目录失败：%v", err)
//	}
//
//	// 3. 解析匹配规则（拆分为通配符列表）
//	matchList := strings.Split(matchPatterns, ",")
//	// 清理空规则
//	for i := len(matchList) - 1; i >= 0; i-- {
//		matchList[i] = strings.TrimSpace(matchList[i])
//		if matchList[i] == "" {
//			matchList = append(matchList[:i], matchList[i+1:]...)
//		}
//	}
//
//	// 4. 解析忽略目录规则
//	ignoreList := make(map[string]bool)
//	for _, dir := range strings.Split(ignoreDirs, ",") {
//		dir = strings.TrimSpace(dir)
//		if dir != "" {
//			ignoreList[dir] = true
//		}
//	}
//
//	// 5. 扫描目录，收集路由包（核心：通配符匹配）
//	var routes []RouteGenInfo
//	err := filepath.Walk(scanRoot, func(path string, info os.FileInfo, err error) error {
//		if err != nil {
//			return err
//		}
//
//		// 跳过非目录、根目录、忽略目录
//		if !info.IsDir() || path == scanRoot || ignoreList[filepath.Base(path)] {
//			return nil
//		}
//
//		// 获取当前目录的基础名（如handler/user → user；orderRoute → orderRoute）
//		dirBase := filepath.Base(path)
//		// 获取当前目录的完整相对路径（用于匹配handler/*这类路径规则）
//		relPath, _ := filepath.Rel(scanRoot, path)
//		// 统一转为斜杠（兼容Windows）
//		relPath = filepath.ToSlash(relPath)
//
//		// 遍历所有匹配规则，只要满足一个就视为匹配成功
//		matchSuccess := false
//		for _, pattern := range matchList {
//			// 规则1：匹配目录基础名（如*Route、*router）
//			if ok, _ := filepath.Match(pattern, dirBase); ok {
//				matchSuccess = true
//				break
//			}
//			// 规则2：匹配完整相对路径（如handler/*）
//			if ok, _ := filepath.Match(pattern, relPath); ok {
//				matchSuccess = true
//				break
//			}
//		}
//
//		// 匹配成功则加入路由列表
//		if matchSuccess {
//			routes = append(routes, RouteGenInfo{
//				ModuleName: moduleName,
//				Path:       relPath,
//			})
//			fmt.Printf("[go-common] 匹配到路由包：%s/%s\n", moduleName, relPath)
//		}
//		return nil
//	})
//	if err != nil {
//		return fmt.Errorf("扫描路由目录失败：%v", err)
//	}
//
//	// 6. 生成导入代码
//	config := RouteGenConfig{
//		PackageName: filepath.Base(outputDir), // 包名默认是目录名（routes）
//		Routes:      routes,
//	}
//	tpl, err := template.New("routeImport").Parse(routeImportTpl)
//	if err != nil {
//		return fmt.Errorf("解析模板失败：%v", err)
//	}
//
//	// 7. 写入auto_import.go文件
//	outputFile := filepath.Join(outputDir, "auto_import.go")
//	f, err := os.Create(outputFile)
//	if err != nil {
//		return fmt.Errorf("创建auto_import.go失败：%v", err)
//	}
//	defer f.Close()
//	if err := tpl.Execute(f, config); err != nil {
//		return fmt.Errorf("生成auto_import.go内容失败：%v", err)
//	}
//
//	// ========== 新增核心逻辑：检查并注入业务main.go ==========
//	if len(routes) > 0 { // 仅当有路由包时才检查
//		// 1. 查找业务项目的main.go
//		mainGoPath, err := findMainGo(scanRoot)
//		if err != nil {
//			fmt.Printf("[go-common] 警告：查找main.go失败（不影响路由生成）：%v\n", err)
//		} else {
//			// 2. 检查是否已调用routes.Init()
//			//hasInit, err := checkMainHasRoutesInit(mainGoPath)
//			hasInit, err := CheckMainHasValidRoutesInit(mainGoPath, moduleName, outputDir)
//			if err != nil {
//				fmt.Printf("[go-common] 警告：检查main.go的routes.Init()失败：%v\n", err)
//			} else if !hasInit { // 3. 未调用则自动注入
//				//if err := injectRoutesInitToMain(mainGoPath, moduleName, outputDir); err != nil {
//				if err := InjectRoutesInitToMain(mainGoPath, moduleName, outputDir); err != nil {
//					fmt.Printf("[go-common] 警告：自动注入routes.Init()失败，请手动添加：%v\n", err)
//				}
//			} else {
//				fmt.Printf("[go-common] main.go已包含routes.Init()调用，无需注入\n")
//			}
//		}
//	}
//	fmt.Printf("[go-common] 成功生成路由导入文件：%s（共%d个路由包）\n", outputFile, len(routes))
//	return nil
//}
//
//// ---------------------- 新增：业务main.go检查+注入逻辑 ----------------------
//// findMainGo 查找业务项目的main.go文件（从扫描根目录向下找）
//func findMainGo(scanRoot string) (string, error) {
//	var mainPath string
//	err := filepath.Walk(scanRoot, func(path string, info os.FileInfo, err error) error {
//		if err != nil {
//			return err
//		}
//		// 找到main.go文件（且是main包）
//		if !info.IsDir() && strings.HasSuffix(path, "main.go") {
//			// 快速检查是否是main包（避免匹配测试文件）
//			file, err := os.Open(path)
//			if err != nil {
//				return nil // 跳过无法读取的文件
//			}
//			defer file.Close()
//
//			scanner := bufio.NewScanner(file)
//			for scanner.Scan() {
//				line := strings.TrimSpace(scanner.Text())
//				if line == "package main" {
//					mainPath = path
//					return filepath.SkipAll // 找到后终止遍历
//				}
//			}
//		}
//		return nil
//	})
//	if err != nil {
//		return "", fmt.Errorf("遍历查找main.go失败：%v", err)
//	}
//	if mainPath == "" {
//		return "", fmt.Errorf("在扫描目录[%s]下未找到main包的main.go文件", scanRoot)
//	}
//	return mainPath, nil
//}
//
//// checkMainHasRoutesInit 检查业务main.go是否调用了routes.Init()
//func checkMainHasRoutesInit(mainGoPath string) (bool, error) {
//	// 解析main.go的AST语法树
//	fset := token.NewFileSet()
//	file, err := parser.ParseFile(fset, mainGoPath, nil, parser.AllErrors)
//	if err != nil {
//		return false, fmt.Errorf("解析main.go失败：%v", err)
//	}
//
//	hasInit := false
//	// 遍历AST找main函数中的routes.Init()调用
//	ast.Inspect(file, func(n ast.Node) bool {
//		// 匹配main函数声明
//		funcDecl, ok := n.(*ast.FuncDecl)
//		if ok && funcDecl.Name.Name == "main" && funcDecl.Type.Results == nil {
//			// 遍历main函数体的所有语句
//			for _, stmt := range funcDecl.Body.List {
//				// 匹配表达式语句（如 routes.Init()）
//				exprStmt, ok := stmt.(*ast.ExprStmt)
//				if !ok {
//					continue
//				}
//				// 匹配函数调用
//				callExpr, ok := exprStmt.X.(*ast.CallExpr)
//				if !ok {
//					continue
//				}
//				// 匹配routes.Init选择器
//				selExpr, ok := callExpr.Fun.(*ast.SelectorExpr)
//				if !ok {
//					continue
//				}
//				// 匹配包名和函数名
//				ident, ok := selExpr.X.(*ast.Ident)
//				if ok && ident.Name == "routes" && selExpr.Sel.Name == "Init" {
//					hasInit = true
//					return false // 找到后终止遍历
//				}
//			}
//		}
//		return true
//	})
//
//	// 额外检查：是否导入了routes包
//	hasRoutesImport := false
//	for _, imp := range file.Imports {
//		importPath := strings.Trim(imp.Path.Value, `"`)
//		if importPath == "routes" || strings.HasSuffix(importPath, "/routes") {
//			hasRoutesImport = true
//			break
//		}
//	}
//
//	// 必须同时满足：导入routes包 + 调用routes.Init()
//	return hasInit && hasRoutesImport, nil
//}
//
//// injectRoutesInitToMain 给业务项目的main.go自动注入routes包导入和Init()调用
//// 参数说明：
////
////	mainGoPath: 业务项目main.go的绝对/相对路径（如：/usr/local/work/pano-material/main.go）
////	moduleName: 业务项目的go mod名称（如：pano-material，从go.mod解析的）
////	outputDir: 路由文件输出目录（如：routes，即auto_import.go所在目录）
//func injectRoutesInitToMain(mainGoPath, moduleName, outputDir string) error {
//	// -------------------------- 步骤1：准备通用参数 --------------------------
//	// 1. 动态生成routes包的导入路径（核心：通用化）
//	// 示例：moduleName=pano-material + outputDir=routes → "pano-material/routes"
//	// 示例：moduleName=new-project + outputDir=gen/routes → "new-project/gen/routes"
//	routesImportPath := fmt.Sprintf("%s/%s", moduleName, outputDir)
//	routesImportPath = filepath.ToSlash(filepath.Clean(routesImportPath)) // 清理路径（避免//、../）
//
//	// 2. 路由包的调用别名（默认取outputDir最后一级，如gen/routes → routes）
//	routesAlias := filepath.Base(outputDir)
//	// 处理特殊情况：如果outputDir是根目录（如/），别名默认用routes
//	if routesAlias == "." || routesAlias == "/" {
//		routesAlias = "routes"
//	}
//
//	// -------------------------- 步骤2：读取main.go内容 --------------------------
//	// 读取文件内容并按行拆分
//	content, err := os.ReadFile(mainGoPath)
//	if err != nil {
//		return fmt.Errorf("读取main.go失败：%w", err)
//	}
//	lines := strings.Split(string(content), "\n")
//	originalLines := make([]string, len(lines)) // 备份原内容
//	copy(originalLines, lines)
//
//	// -------------------------- 步骤3：自动添加routes包导入 --------------------------
//	hasRoutesImport := false // 是否已导入routes包
//	importBlockEndLine := -1 // import ( ... ) 块的结束行号
//	packageMainLine := -1    // package main所在行号
//
//	// 遍历每行，找关键信息
//	for i, line := range lines {
//		trimLine := strings.TrimSpace(line)
//
//		// 记录package main的行号
//		if trimLine == "package main" {
//			packageMainLine = i
//		}
//
//		// 检查是否已导入目标routes包
//		if strings.Contains(trimLine, fmt.Sprintf(`"%s"`, routesImportPath)) {
//			hasRoutesImport = true
//		}
//
//		// 记录import ( ... ) 块的结束行（如import (下的最后一行)）
//		if trimLine == ")" && importBlockEndLine == -1 {
//			// 确认上一行是import (开头
//			if i > 0 && strings.HasPrefix(strings.TrimSpace(lines[i-1]), "import (") {
//				importBlockEndLine = i
//			}
//		}
//	}
//
//	// 如果没导入routes包，自动添加
//	if !hasRoutesImport {
//		// 情况1：有import ( ... ) 块 → 插入到块内最后一行
//		if importBlockEndLine > 0 {
//			// 构造导入行（保持和其他导入一致的缩进，默认用\t）
//			importLine := fmt.Sprintf("\t\"%s\"", routesImportPath)
//			// 在import块结束前插入
//			newLines := append(lines[:importBlockEndLine], importLine)
//			newLines = append(newLines, lines[importBlockEndLine:]...)
//			lines = newLines
//		} else {
//			// 情况2：无import块 → 在package main后添加单行import
//			if packageMainLine == -1 {
//				return fmt.Errorf("main.go中未找到package main声明，无法添加导入")
//			}
//			// 构造单行导入
//			importLine := fmt.Sprintf("import \"%s\"", routesImportPath)
//			// 插入到package main下一行
//			newLines := append(lines[:packageMainLine+1], importLine)
//			newLines = append(newLines, lines[packageMainLine+1:]...)
//			lines = newLines
//		}
//		fmt.Printf("[go-common] 自动为main.go添加导入：%s\n", routesImportPath)
//	}
//
//	// -------------------------- 步骤4：自动插入routes.Init()调用 --------------------------
//	mainFuncStartLine := -1 // func main() { 的行号
//	// 遍历找main函数开头
//	for i, line := range lines {
//		trimLine := strings.TrimSpace(line)
//		if trimLine == "func main() {" {
//			mainFuncStartLine = i
//			break
//		}
//	}
//
//	if mainFuncStartLine == -1 {
//		return fmt.Errorf("main.go中未找到func main() {}函数，无法插入Init()调用")
//	}
//
//	// 检查是否已存在Init()调用（避免重复插入）
//	hasInitCall := false
//	for i := mainFuncStartLine + 1; i < len(lines); i++ {
//		trimLine := strings.TrimSpace(lines[i])
//		// 匹配：routes.Init() / gen_routes.Init() 等
//		if strings.HasPrefix(trimLine, fmt.Sprintf("%s.Init()", routesAlias)) {
//			hasInitCall = true
//			break
//		}
//	}
//
//	// 如果没有Init()调用，插入到main函数第一行
//	if !hasInitCall {
//		// 匹配原有缩进（比如func main() { 前面有2个\t，就用同样的缩进）
//		indent := strings.Repeat("\t", strings.Count(lines[mainFuncStartLine], "\t"))
//		// 构造Init()调用行
//		initCallLine := fmt.Sprintf("%s%s.Init()", indent, routesAlias)
//		// 插入到func main() { 的下一行
//		newLines := append(lines[:mainFuncStartLine+1], initCallLine)
//		newLines = append(newLines, lines[mainFuncStartLine+1:]...)
//		lines = newLines
//		fmt.Printf("[go-common] 自动为main.go插入调用：%s.Init()\n", routesAlias)
//	}
//
//	// -------------------------- 步骤5：写回main.go --------------------------
//	// 只有内容变化时才写入（避免覆盖原文件）
//	newContent := strings.Join(lines, "\n")
//	if newContent != strings.Join(originalLines, "\n") {
//		if err := os.WriteFile(mainGoPath, []byte(newContent), 0644); err != nil {
//			return fmt.Errorf("写入main.go失败：%w", err)
//		}
//		fmt.Printf("[go-common] main.go已自动更新完成\n")
//	} else {
//		fmt.Printf("[go-common] main.go无需更新（已包含routes导入和Init()调用）\n")
//	}
//
//	return nil
//}
//
//// InjectRoutesInitToMain 自动给业务main.go注入routes.Init()（含导入语句+函数调用）
//func InjectRoutesInitToMain(mainGoPath, moduleName, outputDir string) error {
//
//	// 1. 先检查是否已存在有效代码（避免重复）
//	hasValid, err := CheckMainHasValidRoutesInit(mainGoPath, moduleName, outputDir)
//	if err != nil {
//		return err
//	}
//	if hasValid {
//		fmt.Println("INFO: 已存在有效routes.Init()调用，无需注入")
//		return nil
//	}
//
//	// 1. 读取main.go内容
//	content, err := os.ReadFile(mainGoPath)
//	if err != nil {
//		return fmt.Errorf("读取main.go失败：%v", err)
//	}
//	lines := strings.Split(string(content), "\n")
//	// 2. 步骤1：检查是否导入routes包，无则添加
//	hasRoutesImport := false
//	importEndLine := -1
//	for i, line := range lines {
//		trimmed := strings.TrimSpace(line)
//		// 匹配导入语句
//		if strings.HasPrefix(trimmed, "import (") || strings.HasPrefix(trimmed, "import \"") {
//			if strings.Contains(trimmed, "routes") {
//				hasRoutesImport = true
//			}
//		}
//		// 记录import块结束位置
//		if trimmed == ")" && importEndLine == -1 && i > 0 && strings.HasPrefix(strings.TrimSpace(lines[i-1]), "import (") {
//			importEndLine = i
//		}
//	}
//	// 无routes导入则添加
//	if !hasRoutesImport {
//		if importEndLine == -1 {
//			// 无import块，在package main后添加
//			packageLine := -1
//			for i, line := range lines {
//				if strings.TrimSpace(line) == "package main" {
//					packageLine = i
//					break
//				}
//			}
//			if packageLine == -1 {
//				return fmt.Errorf("main.go中未找到package main声明")
//			}
//			// 在package main后插入导入
//			newLines := append(lines[:packageLine+1], `import "pano-material/routes"`)
//			newLines = append(newLines, lines[packageLine+1:]...)
//			lines = newLines
//		} else {
//			// 有import块，在块内添加
//			newLines := append(lines[:importEndLine], `	"pano-material/routes"`)
//			newLines = append(newLines, lines[importEndLine:]...)
//			lines = newLines
//		}
//		fmt.Printf("[go-common] 已为main.go添加routes包导入\n")
//	}
//	// 3. 步骤2：在main函数第一行插入routes.Init()
//	mainFuncLine := -1
//	for i, line := range lines {
//		trimmed := strings.TrimSpace(line)
//		if trimmed == "func main() {" {
//			mainFuncLine = i
//			break
//		}
//	}
//	if mainFuncLine == -1 {
//		return fmt.Errorf("main.go中未找到func main() {}声明")
//	}
//	// 插入调用语句（保持缩进和原有代码对齐）
//	indent := strings.Repeat("\t", strings.Count(lines[mainFuncLine], "\t")) // 匹配原有缩进
//	newLines := append(lines[:mainFuncLine+1], fmt.Sprintf("%sroutes.Init()", indent))
//	newLines = append(newLines, lines[mainFuncLine+1:]...)
//	lines = newLines
//	// 4. 写回main.go
//	newContent := strings.Join(lines, "\n")
//	if err := os.WriteFile(mainGoPath, []byte(newContent), 0644); err != nil {
//		return fmt.Errorf("写入main.go失败：%v", err)
//	}
//	fmt.Printf("[go-common] 已自动为main.go注入routes.Init()调用\n")
//	// 3. 注入后再次检查，确保只写入一次
//	newHasValid, _ := CheckMainHasValidRoutesInit(mainGoPath, moduleName, outputDir)
//	if !newHasValid {
//		return fmt.Errorf("注入后仍未检测到有效代码")
//	}
//
//	return nil
//}
//
//// CheckMainHasValidRoutesInit 精准检查：过滤注释，只识别有效代码
//// 返回值：hasValid（是否有效导入+调用）、err（错误）
//func CheckMainHasValidRoutesInit(mainGoPath, moduleName, outputDir string) (bool, error) {
//	// 1. 动态生成路由包路径/别名
//	routesImportPath := fmt.Sprintf("%s/%s", moduleName, outputDir)
//	routesImportPath = filepath.ToSlash(filepath.Clean(routesImportPath))
//	routesAlias := filepath.Base(outputDir)
//	if routesAlias == "." || routesAlias == "/" {
//		routesAlias = "routes"
//	}
//	// 2. 解析AST（保留注释，但后续过滤）
//	fset := token.NewFileSet()
//	file, err := parser.ParseFile(fset, mainGoPath, nil, parser.ParseComments|parser.AllErrors)
//	if err != nil {
//		return false, err
//	}
//	// 3. 检查「有效」的路由包导入（排除注释）
//	hasValidImport := false
//	for _, imp := range file.Imports {
//		// 跳过被注释的导入（imp.Comment != nil 表示导入行有注释）
//		if imp.Comment != nil {
//			continue
//		}
//		// 跳过在注释块中的导入
//		if isNodeInComment(fset, file, imp.Pos()) {
//			continue
//		}
//		// 匹配导入路径
//		impPath := strings.Trim(imp.Path.Value, `"`)
//		if impPath == routesImportPath {
//			hasValidImport = true
//			break
//		}
//	}
//
//	// 4. 检查「有效」的routes.Init()调用（排除注释）
//	hasValidCall := false
//	ast.Inspect(file, func(n ast.Node) bool {
//		// 跳过注释节点
//		if _, isComment := n.(*ast.Comment); isComment {
//			return false
//		}
//		if _, isCommentGroup := n.(*ast.CommentGroup); isCommentGroup {
//			return false
//		}
//
//		// 匹配main函数
//		funcDecl, ok := n.(*ast.FuncDecl)
//		if !ok || funcDecl.Name.Name != "main" || funcDecl.Type.Results != nil {
//			return true
//		}
//
//		// 遍历main函数体
//		for _, stmt := range funcDecl.Body.List {
//			// 跳过空语句/注释相关语句
//			if stmt == nil {
//				continue
//			}
//
//			// 匹配表达式语句（如 routes.Init()）
//			exprStmt, ok := stmt.(*ast.ExprStmt)
//			if !ok {
//				continue
//			}
//
//			// 匹配函数调用
//			callExpr, ok := exprStmt.X.(*ast.CallExpr)
//			if !ok {
//				continue
//			}
//
//			// 匹配routes.Init选择器
//			selExpr, ok := callExpr.Fun.(*ast.SelectorExpr)
//			if !ok {
//				continue
//			}
//
//			// 匹配包别名和函数名
//			ident, ok := selExpr.X.(*ast.Ident)
//			if ok && ident.Name == routesAlias && selExpr.Sel.Name == "Init" {
//				// 检查是否在注释中
//				if !isNodeInComment(fset, file, stmt.Pos()) {
//					hasValidCall = true
//					return false
//				}
//			}
//		}
//		return true
//	})
//	return hasValidImport && hasValidCall, nil
//}
//
//// isNodeInComment 检查节点是否在注释块中
//func isNodeInComment(fset *token.FileSet, file *ast.File, pos token.Pos) bool {
//	for _, cg := range file.Comments {
//		if cg.Pos() <= pos && pos <= cg.End() {
//			return true
//		}
//	}
//	return false
//}
